/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingTvRouteImport } from './routes/ranking-tv'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedX1AnalyticsRouteImport } from './routes/_authenticated/x1-analytics'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as AuthenticatedVendedoresRouteImport } from './routes/_authenticated/vendedores'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSopsRouteImport } from './routes/_authenticated/sops'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedQuizRouteImport } from './routes/_authenticated/quiz'
import { Route as AuthenticatedMetaAdsRouteImport } from './routes/_authenticated/meta-ads'
import { Route as AuthenticatedHtKanbanSdrRouteImport } from './routes/_authenticated/ht-kanban-sdr'
import { Route as AuthenticatedHtKanbanCloserRouteImport } from './routes/_authenticated/ht-kanban-closer'
import { Route as AuthenticatedHtApiRouteImport } from './routes/_authenticated/ht-api'
import { Route as AuthenticatedHtAnalyticsRouteImport } from './routes/_authenticated/ht-analytics'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFlowsIndexRouteImport } from './routes/_authenticated/flows.index'
import { Route as ApiPublicIgImageRouteImport } from './routes/api/public/ig-image'
import { Route as AuthenticatedFlowsFlowIdRouteImport } from './routes/_authenticated/flows.$flowId'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicNotificationAiReplyRouteImport } from './routes/api/public/notification-ai/reply'
import { Route as ApiPublicNotificationAiContinueRouteImport } from './routes/api/public/notification-ai/continue'
import { Route as ApiPublicHtQuizSubmitRouteImport } from './routes/api/public/ht-quiz/submit'
import { Route as ApiPublicHooksTaskDueCheckRouteImport } from './routes/api/public/hooks/task-due-check'
import { Route as ApiPublicHooksSendCallAnalyticsRouteImport } from './routes/api/public/hooks/send-call-analytics'
import { Route as ApiPublicHooksSendAdsAnalyticsRouteImport } from './routes/api/public/hooks/send-ads-analytics'
import { Route as ApiPublicHooksNotifyTaskCreatedRouteImport } from './routes/api/public/hooks/notify-task-created'
import { Route as ApiPublicHooksDispatchWorkerRouteImport } from './routes/api/public/hooks/dispatch-worker'
import { Route as ApiPublicHooksCallsTickRouteImport } from './routes/api/public/hooks/calls-tick'

const RankingTvRoute = RankingTvRouteImport.update({
  id: '/ranking-tv',
  path: '/ranking-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedX1AnalyticsRoute =
  AuthenticatedX1AnalyticsRouteImport.update({
    id: '/x1-analytics',
    path: '/x1-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedoresRoute = AuthenticatedVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopsRoute = AuthenticatedSopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizRoute = AuthenticatedQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetaAdsRoute = AuthenticatedMetaAdsRouteImport.update({
  id: '/meta-ads',
  path: '/meta-ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHtKanbanSdrRoute =
  AuthenticatedHtKanbanSdrRouteImport.update({
    id: '/ht-kanban-sdr',
    path: '/ht-kanban-sdr',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHtKanbanCloserRoute =
  AuthenticatedHtKanbanCloserRouteImport.update({
    id: '/ht-kanban-closer',
    path: '/ht-kanban-closer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHtApiRoute = AuthenticatedHtApiRouteImport.update({
  id: '/ht-api',
  path: '/ht-api',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHtAnalyticsRoute =
  AuthenticatedHtAnalyticsRouteImport.update({
    id: '/ht-analytics',
    path: '/ht-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlowsIndexRoute = AuthenticatedFlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIgImageRoute = ApiPublicIgImageRouteImport.update({
  id: '/api/public/ig-image',
  path: '/api/public/ig-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFlowsFlowIdRoute =
  AuthenticatedFlowsFlowIdRouteImport.update({
    id: '/flows/$flowId',
    path: '/flows/$flowId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationAiReplyRoute =
  ApiPublicNotificationAiReplyRouteImport.update({
    id: '/api/public/notification-ai/reply',
    path: '/api/public/notification-ai/reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationAiContinueRoute =
  ApiPublicNotificationAiContinueRouteImport.update({
    id: '/api/public/notification-ai/continue',
    path: '/api/public/notification-ai/continue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHtQuizSubmitRoute = ApiPublicHtQuizSubmitRouteImport.update({
  id: '/api/public/ht-quiz/submit',
  path: '/api/public/ht-quiz/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTaskDueCheckRoute =
  ApiPublicHooksTaskDueCheckRouteImport.update({
    id: '/api/public/hooks/task-due-check',
    path: '/api/public/hooks/task-due-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendCallAnalyticsRoute =
  ApiPublicHooksSendCallAnalyticsRouteImport.update({
    id: '/api/public/hooks/send-call-analytics',
    path: '/api/public/hooks/send-call-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendAdsAnalyticsRoute =
  ApiPublicHooksSendAdsAnalyticsRouteImport.update({
    id: '/api/public/hooks/send-ads-analytics',
    path: '/api/public/hooks/send-ads-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifyTaskCreatedRoute =
  ApiPublicHooksNotifyTaskCreatedRouteImport.update({
    id: '/api/public/hooks/notify-task-created',
    path: '/api/public/hooks/notify-task-created',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchWorkerRoute =
  ApiPublicHooksDispatchWorkerRouteImport.update({
    id: '/api/public/hooks/dispatch-worker',
    path: '/api/public/hooks/dispatch-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCallsTickRoute = ApiPublicHooksCallsTickRouteImport.update({
  id: '/api/public/hooks/calls-tick',
  path: '/api/public/hooks/calls-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ranking-tv': typeof RankingTvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ht-analytics': typeof AuthenticatedHtAnalyticsRoute
  '/ht-api': typeof AuthenticatedHtApiRoute
  '/ht-kanban-closer': typeof AuthenticatedHtKanbanCloserRoute
  '/ht-kanban-sdr': typeof AuthenticatedHtKanbanSdrRoute
  '/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/x1-analytics': typeof AuthenticatedX1AnalyticsRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/flows/': typeof AuthenticatedFlowsIndexRoute
  '/api/public/hooks/calls-tick': typeof ApiPublicHooksCallsTickRoute
  '/api/public/hooks/dispatch-worker': typeof ApiPublicHooksDispatchWorkerRoute
  '/api/public/hooks/notify-task-created': typeof ApiPublicHooksNotifyTaskCreatedRoute
  '/api/public/hooks/send-ads-analytics': typeof ApiPublicHooksSendAdsAnalyticsRoute
  '/api/public/hooks/send-call-analytics': typeof ApiPublicHooksSendCallAnalyticsRoute
  '/api/public/hooks/task-due-check': typeof ApiPublicHooksTaskDueCheckRoute
  '/api/public/ht-quiz/submit': typeof ApiPublicHtQuizSubmitRoute
  '/api/public/notification-ai/continue': typeof ApiPublicNotificationAiContinueRoute
  '/api/public/notification-ai/reply': typeof ApiPublicNotificationAiReplyRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ranking-tv': typeof RankingTvRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/chat': typeof AuthenticatedChatRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/ht-analytics': typeof AuthenticatedHtAnalyticsRoute
  '/ht-api': typeof AuthenticatedHtApiRoute
  '/ht-kanban-closer': typeof AuthenticatedHtKanbanCloserRoute
  '/ht-kanban-sdr': typeof AuthenticatedHtKanbanSdrRoute
  '/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/quiz': typeof AuthenticatedQuizRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sops': typeof AuthenticatedSopsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vendedores': typeof AuthenticatedVendedoresRoute
  '/vendor': typeof AuthenticatedVendorRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/x1-analytics': typeof AuthenticatedX1AnalyticsRoute
  '/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/flows': typeof AuthenticatedFlowsIndexRoute
  '/api/public/hooks/calls-tick': typeof ApiPublicHooksCallsTickRoute
  '/api/public/hooks/dispatch-worker': typeof ApiPublicHooksDispatchWorkerRoute
  '/api/public/hooks/notify-task-created': typeof ApiPublicHooksNotifyTaskCreatedRoute
  '/api/public/hooks/send-ads-analytics': typeof ApiPublicHooksSendAdsAnalyticsRoute
  '/api/public/hooks/send-call-analytics': typeof ApiPublicHooksSendCallAnalyticsRoute
  '/api/public/hooks/task-due-check': typeof ApiPublicHooksTaskDueCheckRoute
  '/api/public/ht-quiz/submit': typeof ApiPublicHtQuizSubmitRoute
  '/api/public/notification-ai/continue': typeof ApiPublicNotificationAiContinueRoute
  '/api/public/notification-ai/reply': typeof ApiPublicNotificationAiReplyRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/ranking-tv': typeof RankingTvRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/ht-analytics': typeof AuthenticatedHtAnalyticsRoute
  '/_authenticated/ht-api': typeof AuthenticatedHtApiRoute
  '/_authenticated/ht-kanban-closer': typeof AuthenticatedHtKanbanCloserRoute
  '/_authenticated/ht-kanban-sdr': typeof AuthenticatedHtKanbanSdrRoute
  '/_authenticated/meta-ads': typeof AuthenticatedMetaAdsRoute
  '/_authenticated/quiz': typeof AuthenticatedQuizRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/sops': typeof AuthenticatedSopsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vendedores': typeof AuthenticatedVendedoresRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/_authenticated/x1-analytics': typeof AuthenticatedX1AnalyticsRoute
  '/_authenticated/flows/$flowId': typeof AuthenticatedFlowsFlowIdRoute
  '/api/public/ig-image': typeof ApiPublicIgImageRoute
  '/_authenticated/flows/': typeof AuthenticatedFlowsIndexRoute
  '/api/public/hooks/calls-tick': typeof ApiPublicHooksCallsTickRoute
  '/api/public/hooks/dispatch-worker': typeof ApiPublicHooksDispatchWorkerRoute
  '/api/public/hooks/notify-task-created': typeof ApiPublicHooksNotifyTaskCreatedRoute
  '/api/public/hooks/send-ads-analytics': typeof ApiPublicHooksSendAdsAnalyticsRoute
  '/api/public/hooks/send-call-analytics': typeof ApiPublicHooksSendCallAnalyticsRoute
  '/api/public/hooks/task-due-check': typeof ApiPublicHooksTaskDueCheckRoute
  '/api/public/ht-quiz/submit': typeof ApiPublicHtQuizSubmitRoute
  '/api/public/notification-ai/continue': typeof ApiPublicNotificationAiContinueRoute
  '/api/public/notification-ai/reply': typeof ApiPublicNotificationAiReplyRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ranking-tv'
    | '/admin'
    | '/calendar'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/financeiro'
    | '/ht-analytics'
    | '/ht-api'
    | '/ht-kanban-closer'
    | '/ht-kanban-sdr'
    | '/meta-ads'
    | '/quiz'
    | '/ranking'
    | '/relatorios'
    | '/sops'
    | '/tasks'
    | '/vendedores'
    | '/vendor'
    | '/whatsapp'
    | '/x1-analytics'
    | '/flows/$flowId'
    | '/api/public/ig-image'
    | '/flows/'
    | '/api/public/hooks/calls-tick'
    | '/api/public/hooks/dispatch-worker'
    | '/api/public/hooks/notify-task-created'
    | '/api/public/hooks/send-ads-analytics'
    | '/api/public/hooks/send-call-analytics'
    | '/api/public/hooks/task-due-check'
    | '/api/public/ht-quiz/submit'
    | '/api/public/notification-ai/continue'
    | '/api/public/notification-ai/reply'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ranking-tv'
    | '/admin'
    | '/calendar'
    | '/chat'
    | '/crm'
    | '/dashboard'
    | '/financeiro'
    | '/ht-analytics'
    | '/ht-api'
    | '/ht-kanban-closer'
    | '/ht-kanban-sdr'
    | '/meta-ads'
    | '/quiz'
    | '/ranking'
    | '/relatorios'
    | '/sops'
    | '/tasks'
    | '/vendedores'
    | '/vendor'
    | '/whatsapp'
    | '/x1-analytics'
    | '/flows/$flowId'
    | '/api/public/ig-image'
    | '/flows'
    | '/api/public/hooks/calls-tick'
    | '/api/public/hooks/dispatch-worker'
    | '/api/public/hooks/notify-task-created'
    | '/api/public/hooks/send-ads-analytics'
    | '/api/public/hooks/send-call-analytics'
    | '/api/public/hooks/task-due-check'
    | '/api/public/ht-quiz/submit'
    | '/api/public/notification-ai/continue'
    | '/api/public/notification-ai/reply'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/ranking-tv'
    | '/_authenticated/admin'
    | '/_authenticated/calendar'
    | '/_authenticated/chat'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/ht-analytics'
    | '/_authenticated/ht-api'
    | '/_authenticated/ht-kanban-closer'
    | '/_authenticated/ht-kanban-sdr'
    | '/_authenticated/meta-ads'
    | '/_authenticated/quiz'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/sops'
    | '/_authenticated/tasks'
    | '/_authenticated/vendedores'
    | '/_authenticated/vendor'
    | '/_authenticated/whatsapp'
    | '/_authenticated/x1-analytics'
    | '/_authenticated/flows/$flowId'
    | '/api/public/ig-image'
    | '/_authenticated/flows/'
    | '/api/public/hooks/calls-tick'
    | '/api/public/hooks/dispatch-worker'
    | '/api/public/hooks/notify-task-created'
    | '/api/public/hooks/send-ads-analytics'
    | '/api/public/hooks/send-call-analytics'
    | '/api/public/hooks/task-due-check'
    | '/api/public/ht-quiz/submit'
    | '/api/public/notification-ai/continue'
    | '/api/public/notification-ai/reply'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RankingTvRoute: typeof RankingTvRoute
  ApiPublicIgImageRoute: typeof ApiPublicIgImageRoute
  ApiPublicHooksCallsTickRoute: typeof ApiPublicHooksCallsTickRoute
  ApiPublicHooksDispatchWorkerRoute: typeof ApiPublicHooksDispatchWorkerRoute
  ApiPublicHooksNotifyTaskCreatedRoute: typeof ApiPublicHooksNotifyTaskCreatedRoute
  ApiPublicHooksSendAdsAnalyticsRoute: typeof ApiPublicHooksSendAdsAnalyticsRoute
  ApiPublicHooksSendCallAnalyticsRoute: typeof ApiPublicHooksSendCallAnalyticsRoute
  ApiPublicHooksTaskDueCheckRoute: typeof ApiPublicHooksTaskDueCheckRoute
  ApiPublicHtQuizSubmitRoute: typeof ApiPublicHtQuizSubmitRoute
  ApiPublicNotificationAiContinueRoute: typeof ApiPublicNotificationAiContinueRoute
  ApiPublicNotificationAiReplyRoute: typeof ApiPublicNotificationAiReplyRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ranking-tv': {
      id: '/ranking-tv'
      path: '/ranking-tv'
      fullPath: '/ranking-tv'
      preLoaderRoute: typeof RankingTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/x1-analytics': {
      id: '/_authenticated/x1-analytics'
      path: '/x1-analytics'
      fullPath: '/x1-analytics'
      preLoaderRoute: typeof AuthenticatedX1AnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedores': {
      id: '/_authenticated/vendedores'
      path: '/vendedores'
      fullPath: '/vendedores'
      preLoaderRoute: typeof AuthenticatedVendedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sops': {
      id: '/_authenticated/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof AuthenticatedSopsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz': {
      id: '/_authenticated/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof AuthenticatedQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meta-ads': {
      id: '/_authenticated/meta-ads'
      path: '/meta-ads'
      fullPath: '/meta-ads'
      preLoaderRoute: typeof AuthenticatedMetaAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ht-kanban-sdr': {
      id: '/_authenticated/ht-kanban-sdr'
      path: '/ht-kanban-sdr'
      fullPath: '/ht-kanban-sdr'
      preLoaderRoute: typeof AuthenticatedHtKanbanSdrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ht-kanban-closer': {
      id: '/_authenticated/ht-kanban-closer'
      path: '/ht-kanban-closer'
      fullPath: '/ht-kanban-closer'
      preLoaderRoute: typeof AuthenticatedHtKanbanCloserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ht-api': {
      id: '/_authenticated/ht-api'
      path: '/ht-api'
      fullPath: '/ht-api'
      preLoaderRoute: typeof AuthenticatedHtApiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ht-analytics': {
      id: '/_authenticated/ht-analytics'
      path: '/ht-analytics'
      fullPath: '/ht-analytics'
      preLoaderRoute: typeof AuthenticatedHtAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flows/': {
      id: '/_authenticated/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof AuthenticatedFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ig-image': {
      id: '/api/public/ig-image'
      path: '/api/public/ig-image'
      fullPath: '/api/public/ig-image'
      preLoaderRoute: typeof ApiPublicIgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flows/$flowId': {
      id: '/_authenticated/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AuthenticatedFlowsFlowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notification-ai/reply': {
      id: '/api/public/notification-ai/reply'
      path: '/api/public/notification-ai/reply'
      fullPath: '/api/public/notification-ai/reply'
      preLoaderRoute: typeof ApiPublicNotificationAiReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notification-ai/continue': {
      id: '/api/public/notification-ai/continue'
      path: '/api/public/notification-ai/continue'
      fullPath: '/api/public/notification-ai/continue'
      preLoaderRoute: typeof ApiPublicNotificationAiContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ht-quiz/submit': {
      id: '/api/public/ht-quiz/submit'
      path: '/api/public/ht-quiz/submit'
      fullPath: '/api/public/ht-quiz/submit'
      preLoaderRoute: typeof ApiPublicHtQuizSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/task-due-check': {
      id: '/api/public/hooks/task-due-check'
      path: '/api/public/hooks/task-due-check'
      fullPath: '/api/public/hooks/task-due-check'
      preLoaderRoute: typeof ApiPublicHooksTaskDueCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-call-analytics': {
      id: '/api/public/hooks/send-call-analytics'
      path: '/api/public/hooks/send-call-analytics'
      fullPath: '/api/public/hooks/send-call-analytics'
      preLoaderRoute: typeof ApiPublicHooksSendCallAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-ads-analytics': {
      id: '/api/public/hooks/send-ads-analytics'
      path: '/api/public/hooks/send-ads-analytics'
      fullPath: '/api/public/hooks/send-ads-analytics'
      preLoaderRoute: typeof ApiPublicHooksSendAdsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-task-created': {
      id: '/api/public/hooks/notify-task-created'
      path: '/api/public/hooks/notify-task-created'
      fullPath: '/api/public/hooks/notify-task-created'
      preLoaderRoute: typeof ApiPublicHooksNotifyTaskCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-worker': {
      id: '/api/public/hooks/dispatch-worker'
      path: '/api/public/hooks/dispatch-worker'
      fullPath: '/api/public/hooks/dispatch-worker'
      preLoaderRoute: typeof ApiPublicHooksDispatchWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/calls-tick': {
      id: '/api/public/hooks/calls-tick'
      path: '/api/public/hooks/calls-tick'
      fullPath: '/api/public/hooks/calls-tick'
      preLoaderRoute: typeof ApiPublicHooksCallsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHtAnalyticsRoute: typeof AuthenticatedHtAnalyticsRoute
  AuthenticatedHtApiRoute: typeof AuthenticatedHtApiRoute
  AuthenticatedHtKanbanCloserRoute: typeof AuthenticatedHtKanbanCloserRoute
  AuthenticatedHtKanbanSdrRoute: typeof AuthenticatedHtKanbanSdrRoute
  AuthenticatedMetaAdsRoute: typeof AuthenticatedMetaAdsRoute
  AuthenticatedQuizRoute: typeof AuthenticatedQuizRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSopsRoute: typeof AuthenticatedSopsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVendedoresRoute: typeof AuthenticatedVendedoresRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedX1AnalyticsRoute: typeof AuthenticatedX1AnalyticsRoute
  AuthenticatedFlowsFlowIdRoute: typeof AuthenticatedFlowsFlowIdRoute
  AuthenticatedFlowsIndexRoute: typeof AuthenticatedFlowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHtAnalyticsRoute: AuthenticatedHtAnalyticsRoute,
  AuthenticatedHtApiRoute: AuthenticatedHtApiRoute,
  AuthenticatedHtKanbanCloserRoute: AuthenticatedHtKanbanCloserRoute,
  AuthenticatedHtKanbanSdrRoute: AuthenticatedHtKanbanSdrRoute,
  AuthenticatedMetaAdsRoute: AuthenticatedMetaAdsRoute,
  AuthenticatedQuizRoute: AuthenticatedQuizRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSopsRoute: AuthenticatedSopsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVendedoresRoute: AuthenticatedVendedoresRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedX1AnalyticsRoute: AuthenticatedX1AnalyticsRoute,
  AuthenticatedFlowsFlowIdRoute: AuthenticatedFlowsFlowIdRoute,
  AuthenticatedFlowsIndexRoute: AuthenticatedFlowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RankingTvRoute: RankingTvRoute,
  ApiPublicIgImageRoute: ApiPublicIgImageRoute,
  ApiPublicHooksCallsTickRoute: ApiPublicHooksCallsTickRoute,
  ApiPublicHooksDispatchWorkerRoute: ApiPublicHooksDispatchWorkerRoute,
  ApiPublicHooksNotifyTaskCreatedRoute: ApiPublicHooksNotifyTaskCreatedRoute,
  ApiPublicHooksSendAdsAnalyticsRoute: ApiPublicHooksSendAdsAnalyticsRoute,
  ApiPublicHooksSendCallAnalyticsRoute: ApiPublicHooksSendCallAnalyticsRoute,
  ApiPublicHooksTaskDueCheckRoute: ApiPublicHooksTaskDueCheckRoute,
  ApiPublicHtQuizSubmitRoute: ApiPublicHtQuizSubmitRoute,
  ApiPublicNotificationAiContinueRoute: ApiPublicNotificationAiContinueRoute,
  ApiPublicNotificationAiReplyRoute: ApiPublicNotificationAiReplyRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
