// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

type VendorContext = {
  id: number;
  nome?: string | null;
  utm?: string | null;
  expert?: string | null;
  foto_url?: string | null;
  codigo?: string | null;
  ativo?: boolean | null;
  permissoes?: Record<string, unknown> | null;
  wa_channel_ids?: string[] | null;
  workspace_ids?: string[] | null;
};



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function decodeVendorHeader(value: string | null): { id: number; codigo: string } | null {
  if (!value) return null;
  try {
    const json = Buffer.from(value, 'base64').toString('utf-8');
    const parsed = JSON.parse(json);
    const id = Number(parsed?.id);
    const codigo = String(parsed?.codigo ?? '').trim();
    if (!Number.isFinite(id) || id <= 0 || !codigo) return null;
    return { id, codigo };
  } catch {
    try {
      const parsed = JSON.parse(decodeURIComponent(value));
      const id = Number(parsed?.id);
      const codigo = String(parsed?.codigo ?? '').trim();
      if (!Number.isFinite(id) || id <= 0 || !codigo) return null;
      return { id, codigo };
    } catch {
      return null;
    }
  }
}

async function validateVendorSession(supabase: any, request: Request): Promise<VendorContext | null> {
  const rawHeader = request.headers.get('x-vendor-session');
  const decoded = decodeVendorHeader(rawHeader);
  if (!decoded) {
    console.info('[vendor-session] no vendor header on server request', {
      rawHeaderPresent: !!rawHeader,
      rawHeaderLength: rawHeader?.length ?? 0,
    });
    return null;
  }
  console.info('[vendor-session] decoded vendor header', { vendorId: decoded.id, codigo: decoded.codigo });
  let { data, error } = await supabase.rpc('login_vendedor_by_codigo', { _codigo: decoded.codigo });
  if (error || !data) {
    // Tenta validar como membro High Ticket
    const { data: htData, error: htError } = await supabase.rpc('login_ht_team_by_codigo', { _codigo: decoded.codigo });
    if (!htError && htData) {
      data = {
        id: htData.id,
        nome: htData.nome,
        codigo: htData.codigo,
        ativo: htData.ativo,
        permissoes: htData.permissoes,
        expert: "High Ticket",
        wa_channel_ids: [],
        workspace_ids: ["High Ticket"]
      };
    } else {
      console.warn('[vendor-session] invalid vendor/ht code on server', {
        vendorId: decoded.id,
        codigo: decoded.codigo,
        error: error?.message ?? htError?.message ?? null,
      });
      return null;
    }
  }
  const vendor = data as VendorContext;
  if (Number(vendor.id) !== decoded.id) {
    console.warn('[vendor-session] vendor id mismatch', { expected: decoded.id, received: Number(vendor.id) });
    return null;
  }
  console.info('[vendor-session] validated vendor/ht on server', {
    vendorId: Number(vendor.id),
    expert: vendor.expert ?? null,
    channelCount: Array.isArray(vendor.wa_channel_ids) ? vendor.wa_channel_ids.length : 0,
  });
  return {
    ...vendor,
    id: Number(vendor.id),
    wa_channel_ids: Array.isArray(vendor.wa_channel_ids) ? vendor.wa_channel_ids.map(String) : [],
    workspace_ids: Array.isArray(vendor.workspace_ids) ? vendor.workspace_ids.map(String) : null,
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const incomingVendorHeader = request.headers.get('x-vendor-session');
    const authHeader = request.headers.get('authorization');

    console.info('[auth-middleware] incoming headers check', {
      hasVendorHeader: !!incomingVendorHeader,
      vendorHeaderLength: incomingVendorHeader?.length ?? 0,
      hasAuthHeader: !!authHeader,
      url: request.url,
    });

    const baseSupabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            ...(incomingVendorHeader ? { 'x-vendor-session': incomingVendorHeader } : {}),
            ...(authHeader ? { Authorization: authHeader } : {}),
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    // Se existe sessão de vendedor, ela deve prevalecer mesmo que o navegador ainda tenha
    // um token Supabase antigo salvo. Isso evita o vendedor cair nas RLS de admin e receber
    // "Inautorizado" nas telas liberadas pra ele.
    const vendor = await validateVendorSession(baseSupabase, request);
    if (vendor) {
      return next({
        context: {
          supabase: baseSupabase,
          userId: `vendor:${vendor.id}`,
          claims: null as unknown,
          vendor: vendor as VendorContext | null,
        },
      });
    }

    if (!authHeader) {
      console.error('[auth-middleware] REJECTING request — no vendor session AND no auth header', {
        hasVendorHeader: !!incomingVendorHeader,
        vendorDecoded: incomingVendorHeader ? decodeVendorHeader(incomingVendorHeader) : 'no-header',
      });
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims as unknown,
        vendor: null as VendorContext | null,
      },
    });
  },
);
